// Generated by CoffeeScript 1.11.1
(function() {
  window.FileSrcManager = (function() {
    function FileSrcManager(inputIdCount, moduleFactory) {
      this.inputIdCount = inputIdCount;
      this.moduleFactory = moduleFactory;
    }

    FileSrcManager.prototype.setFileSrcToImg = function(inputId, img) {};

    FileSrcManager.prototype.addFile = function(type) {
      var input;
      input = this.moduleFactory.getModuleById("tmpFileSrcHolder");
      $(input).attr("inputId", this.inputIdCount);
      $(input).attr("fileType", type);
      this.inputIdCount++;
      $(input).appendTo($("#fileSrcHolders"));
      return $(input).trigger("click");
    };

    return FileSrcManager;

  })();

}).call(this);

//# sourceMappingURL=fileSrcManager.js.map
