// Generated by CoffeeScript 1.11.1
(function() {
  window.ModuleFactory = (function() {
    function ModuleFactory() {}

    ModuleFactory.prototype.getModuleById = function(id) {
      var ele;
      ele = $(document.getElementById(id)).clone()[0];
      $(ele).removeAttr("id");
      return ele;
    };

    return ModuleFactory;

  })();

}).call(this);

//# sourceMappingURL=moduleFactory.js.map
