// Generated by CoffeeScript 1.11.1

/*$(document.body).on "pointermove", ->
  console.log(1)
 */

(function() {
  var pointerMove;

  $(document).ready(function() {
    return document.getElementById("zhazha").addEventListener("pointermove", pointerMove, false);

    /*$("#zhazha").on "pointermove", (evt)->
      console.log(evt.pressure)
     */
  });

  pointerMove = function(evt) {
    return console.log(evt.pressure);
  };

}).call(this);

//# sourceMappingURL=test.js.map
